"""Self-updating human navigation README at the documents root.

A plain-Markdown index a person browses in a file UI (Nextcloud, Finder, a git host) —
distinct from the OKF aggregates (which are for agents) and from the HTML dashboard
(`app/services/dashboard.py`, richer but needs a browser). Finding-aid principle at the top
of the tree: it points into each top-level folder's aggregate and shows a few at-a-glance
statistics, without duplicating any aggregate's content.

Regenerated at the end of every ingest (when `generate_readme` is set) so it never drifts.
To stay safe next to a user's own README, it writes only a file that either does not exist
or already carries this module's generated-marker — a hand-written `README.md` is never
overwritten; the ingest just logs that it was left alone.
"""

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from app.constants import (
    FOLDER_INDEX_OKF_TYPE,
    FOLDER_SUMMARY_OKF_TYPE,
    MATTERS_DIR_NAME,
    SYNTHESIS_FILENAME,
    SYNTHESIS_OKF_TYPE,
)
from app.models.okf import OKFDocument
from app.services.ingest import folder_summary_path, load_existing_summary

README_FILENAME = "README.md"
GENERATED_MARKER = "<!-- generated by smart-okf — regenerated on each ingest; edits are overwritten -->"
"""Sentinel on line 1 of a smart-okf-owned README. A README without it is treated as the
user's own and never overwritten."""

_VERIFICATION_FLAG_MARKER = "_Verification: FLAGGED"


@dataclass
class NavigationStats:
    """At-a-glance counts computed from the tree for the README header."""

    folders: int = 0
    documents: int = 0
    matters: int = 0
    flagged: int = 0
    has_synthesis: bool = False


def _top_level_concepts(root: Path) -> list[tuple[Path, OKFDocument]]:
    """Immediate subfolders of root that have an aggregate/index, with the loaded concept."""
    concepts: list[tuple[Path, OKFDocument]] = []
    for sub in sorted(p for p in root.iterdir() if p.is_dir() and not p.name.startswith(".")):
        document = load_existing_summary(folder_summary_path(sub))
        if document is not None and document.frontmatter.type in {FOLDER_SUMMARY_OKF_TYPE, FOLDER_INDEX_OKF_TYPE}:
            concepts.append((folder_summary_path(sub), document))
    return concepts


def collect_stats(root: Path) -> NavigationStats:
    """Compute navigation statistics from the aggregates on disk (no LLM, deterministic)."""
    stats = NavigationStats()
    for path in root.rglob("*.md"):
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        document = load_existing_summary(path)
        if document is None:
            continue
        if document.frontmatter.type == FOLDER_SUMMARY_OKF_TYPE:
            stats.folders += 1
            stats.documents += len(document.frontmatter.sources)
            stats.flagged += document.body.count(_VERIFICATION_FLAG_MARKER)
        elif document.frontmatter.type == SYNTHESIS_OKF_TYPE:
            stats.has_synthesis = True
    matters_dir = root / MATTERS_DIR_NAME
    if matters_dir.is_dir():
        stats.matters = sum(1 for p in matters_dir.glob("*.md"))
    return stats


def build_navigation(root: Path, *, now: datetime | None = None) -> str:
    """Render the navigation README markdown (does not write it)."""
    stats = collect_stats(root)
    timestamp = (now or datetime.now()).strftime("%Y-%m-%d %H:%M")
    lines = [
        GENERATED_MARKER,
        "",
        f"# {root.name} — knowledge base",
        "",
        f"_Auto-generated by smart-okf on {timestamp}. Browse the folders below; each has an "
        "aggregate `.md` distilled from its documents._",
        "",
        "## At a glance",
        "",
        f"- **{stats.documents}** document(s) across **{stats.folders}** folder aggregate(s)",
        f"- **{stats.matters}** cross-folder matter(s) in `{MATTERS_DIR_NAME}/`"
        if stats.matters
        else "- no cross-folder matters yet",
    ]
    if stats.has_synthesis:
        lines.append(f"- whole-tree synthesis: [`{SYNTHESIS_FILENAME}`]({SYNTHESIS_FILENAME})")
    if stats.flagged:
        lines.append(f"- ⚠ **{stats.flagged}** extraction(s) flagged by fact verification — see `_Verification:` lines")
    lines.extend(["", "## Folders", ""])

    concepts = _top_level_concepts(root)
    if concepts:
        for path, document in concepts:
            link = path.relative_to(root).as_posix()
            description = document.frontmatter.description or document.frontmatter.title or path.parent.name
            lines.append(f"- [{path.parent.name}]({link}) — {description}")
    else:
        lines.append("_No folder aggregates yet. Run ingest to populate this index._")
    lines.append("")
    return "\n".join(lines)


def write_navigation(root: Path, *, now: datetime | None = None) -> Path | None:
    """Write the navigation README, unless a user-owned README is in the way.

    Returns the path written, or None if a hand-written README (no generated marker) was
    found and left untouched.
    """
    target = root / README_FILENAME
    if target.is_file():
        first_line = target.read_text(encoding="utf-8").splitlines()[:1]
        if not first_line or first_line[0].strip() != GENERATED_MARKER:
            return None
    target.write_text(build_navigation(root, now=now), encoding="utf-8")
    return target
